apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adcs-issuer-serving-cert
  namespace: cert-manager
spec:
  commonName: adcs-issuer-webhook-service.cert-manager.svc
  dnsNames:
  - adcs-issuer-webhook-service.cert-manager.svc.cluster.local
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned
  secretName: webhook-server-cert
