
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-adcs-certmanager-csf-nokia-com-v1-adcsissuer
  failurePolicy: Fail
  name: adcsissuer-mutation.adcs.certmanager.csf.nokia.com
  rules:
  - apiGroups:
    - adcs.certmanager.csf.nokia.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - adcsissuer
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-certmanager-csf-nokia-com-v1-clusteradcsissuer
  failurePolicy: Fail
  name: mclusteradcsissuer.kb.io
  rules:
  - apiGroups:
    - batch.certmanager.csf.nokia.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteradcsissuers

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-adcs-certmanager-csf-nokia-com-v1-adcsissuer
  failurePolicy: Fail
  name: adcsissuer-validation.adcs.certmanager.csf.nokia.com
  rules:
  - apiGroups:
    - adcs.certmanager.csf.nokia.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - adcsissuer
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-certmanager-csf-nokia-com-v1-clusteradcsissuer
  failurePolicy: Fail
  name: vclusteradcsissuer.kb.io
  rules:
  - apiGroups:
    - batch.certmanager.csf.nokia.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusteradcsissuers
